### ISSUE TITLE
1.0 Roadmap

### ISSUE THREAD

**Issue by ricokahler** [ricokahler/next-plugin-preval#1]
This lib is more or less feature-complete and the current API is locked in but I typically like to let my new packages sit for a bit before labeling with a 1.0.

If you see any issues, please file one!

Some other random TODOs:

- [ ] performance audit
- [x] add renovate for automated dep updates
- [ ] add export map and modules entry point
- [ ] data dependencies for data refreshes during development

**Comment by ricokahler** [comment]
Update: I'll probably promote this to 1.0 soon. I've been using it regularly and haven't run into any issues.
